#http://localhost:8080/swagger-ui/index.html

server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/nguoidung"
    username: root
    password: abc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
    cache-names:
      -cache1
      -cache2
    redis:
      time-to-live: 60s
      cache-null-values: true

redis:
  host: localhost
  port: 8080